Big changes
cat-dev-group/pyweek-33 pull request #14
Opened 2022-03-25 18:13 UTC by Oreo4102004

-> added background

-> level_tools , (platform , button , flag)

-> uncomment the things in game.py for a demo usage of them

2022-03-25 20:20 UTC, AbooMinister25 requested changes

2022-03-25 20:20 UTC, AbooMinister25 commented on src/level_tools.py
> +class platform(pyglet.shapes.Rectangle):
Why isn't the class name capitalized? Same goes for the `flag` class.

2022-03-25 20:20 UTC, AbooMinister25 commented on src/level_tools.py
> +class button:
Same thing about class capitalization here

2022-03-25 20:20 UTC, AbooMinister25 commented on src/level_tools.py
> +        self.a = alignment
Why not just make this `self.alignment`? It would pose better for readability

2022-03-25 22:24 UTC, brad90four requested changes

2022-03-25 22:24 UTC, brad90four commented on src/game.py
> +bg = pyglet.resource.image("bg.png")
Could this PR include the image too?

2022-03-26 14:34 UTC, brad90four approved these changes
LGTM, loads of awesome work on this

2022-03-26 14:37 UTC, Kronifer approved these changes
Lgtm

2022-03-26 14:37 UTC, merged